version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio12345
      MINIO_ROOT_PASSWORD: minio12345
    command: server --console-address ":9001" /data
    networks:
      - paralon

  event-redis:
    container_name: event-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - paralon


volumes:
  minio_storage:
  cache:

networks:
  paralon:
